name: CD - Muslim Soul

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t muslim-soul .

    - name: Deploy Docker container
      run: |
        docker stop muslim-soul || true
        docker rm muslim-soul || true
        docker run -d -p 5000:5000 --name muslim-soul muslim-soul
